### ISSUE TITLE
Handle Headers

### ISSUE THREAD

**Issue by dankinder** [dankinder/httpmock#2]
I haven't personally had a need for this yet, but it would be nice at some point to handle expected request headers like so:

```
type HandlerWithHeader interface {
	HandleWithHeader(method, path string, body []byte, header http.Header) Response
}
```

**Comment by cgilling** [comment]
hah! was just thinking I could this library for what I'm working on and was like "would really like header support", and then saw this. Maybe I'll take a quick stab at implementing this and see what you think
