### ISSUE TITLE
Better Header Support

### ISSUE THREAD

**Issue by mikelu92** [dankinder/httpmock#4]
Currently if you want to match headers, you have to provide all the headers, including `Content-Length`, `User-Agent`, etc. For a a matched endpoint. This would be better if it'd just check if the given headers were included instead, and ignore everything else.

I see in the readme there's a reference to a `MatchHeaders` function, but I don't see that anywhere in the code.

**Comment by dankinder** [comment]
Yeah readme had a typo, I just fixed it, see https://github.com/dankinder/httpmock/blob/master/mockhandler.go#L67 those should do what you want
